version: '3.3'

services:
  minio:
    container_name: minio
    hostname: minio-test
    network_mode: host
    image: quay.io/minio/minio
    restart: always
    command:
      - server
      - /data
      - "--console-address"
      - ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9001" ]
      interval: 30s
      timeout: 10s
      retries: 5
  prepare_buckets:
    container_name: minio-setup
    image: quay.io/minio/minio
    network_mode: host
    depends_on:
      minio:
        condition: service_healthy
    entrypoint:
      - "/bin/sh"
      - "-c"
      - |
        mc alias set e2e "http://localhost:9000" minioadmin minioadmin
        mc admin info e2e
        mc mb e2e/tmp && mc mb e2e/lakehouse

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    network_mode: host
    command:
      - "azurite-blob"
      - "--blobHost"
      - "localhost"
      - "--blobPort"
      - "10001"
      - "--skipApiVersionCheck"
  create-cdm-container:
    image: python:3.11-slim-bookworm
    network_mode: host
    depends_on:
      - azurite
    volumes:
      - ./populate-cdm-container.py:/populate-cdm-container.py
    command: [ "/bin/sh", "-c", "pip install azure-storage-blob requests && python /populate-cdm-container.py" ]
  trino:
    depends_on:
      lakekeeper:
        condition: service_healthy
    network_mode: host
    image: "trinodb/trino:474"
    volumes:
      - ./integration-tests.properties:/etc/trino/catalog/iceberg.properties
##  http-proxy:
##    networks:
##      mesh:
##        ipv4_address: 10.1.0.10
##    extra_hosts:
##      - "localhost:10.1.0.10"
##    ports:
##      - "9004:9004"
##      - "9005:9005"
##      - "443:443"
##    image: "envoyproxy/envoy:v1.31.2"
##    command:
##      - envoy
##      - "-c"
##      - /etc/envoy/envoy.yaml
##    volumes:
##      - ./http-proxy-envoy-config.yaml:/etc/envoy/envoy.yaml
  lakekeeper:
    image: quay.io/lakekeeper/catalog:latest-main
    network_mode: host
    environment:
#      - LAKEKEEPER__PG_ENCRYPTION_KEY=This-is-NOT-Secure!
      - LAKEKEEPER__METRICS_PORT=9002
      - LAKEKEEPER__BASE_URI=http://localhost:8181
      - ICEBERG_REST__BASE_URI=http://localhost:8181
      - LAKEKEEPER__BIND_IP=http://localhost:8181
      - LAKEKEEPER__PG_DATABASE_URL_READ=postgresql://postgres:postgres@localhost:5432/postgres
      - LAKEKEEPER__PG_DATABASE_URL_WRITE=postgresql://postgres:postgres@localhost:5432/postgres
      - RUST_LOG=trace,axum=trace,sqlx=trace,iceberg-catalog=trace
    command: [ "serve" ]
    healthcheck:
      test: [ "CMD", "/home/nonroot/iceberg-catalog", "healthcheck" ]
      interval: 1s
      timeout: 10s
      retries: 30
    depends_on:
      lakekeeper_migrate:
        condition: service_completed_successfully
      lakekeeper_db:
        condition: service_healthy
      minio:
        condition: service_healthy
  lakekeeper_migrate:
    image: quay.io/lakekeeper/catalog:latest-main
    network_mode: host
    environment:
#      - LAKEKEEPER__PG_ENCRYPTION_KEY=This-is-NOT-Secure!
      - LAKEKEEPER__PG_DATABASE_URL_READ=postgresql://postgres:postgres@localhost:5432/postgres
      - LAKEKEEPER__PG_DATABASE_URL_WRITE=postgresql://postgres:postgres@localhost:5432/postgres
      - RUST_LOG=info
    restart: "no"
    command: [ "migrate" ]
    depends_on:
      lakekeeper_db:
        condition: service_healthy
  lakekeeper_prepare:
    image: python:3.11-slim-bookworm
    network_mode: host
    environment:
      CATALOG_HOST: localhost
      CATALOG_WAREHOUSE: demo
    depends_on:
      lakekeeper:
        condition: service_healthy
    restart: "no"
    volumes:
      - ./bootstrap-lk.py:/bootstrap-lk.py
    command: [ "/bin/sh", "-c", "pip install requests && python /bootstrap-lk.py"  ]
  lakekeeper_db:
    image: bitnami/postgresql:16.3.0
    network_mode: host
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -p 5432 -d postgres" ]
      interval: 2s
      timeout: 10s
      retries: 2
