apiVersion: streaming.sneaksanddata.com/v1
kind: StreamClass
metadata:
  name: {{ template "app.fullname" . }}-beta
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "streamclass.labels" $ | nindent 4 }}
  {{- if .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  apiGroupRef: streaming.sneaksanddata.com
  kindRef: MicrosoftSynapseBetaStream
  apiVersion: v1
  pluralName: microsoft-synapse-beta-streams
  secretRefs:
    - streamConfigurationSecretRef
